# Generated by Django 3.2.16 on 2023-03-19 17:18

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


def insert_public_tenant_and_domain(apps, schema_editor):
    organization_model = apps.get_model('tenants', 'Organization')
    public_tenant = organization_model.objects.create(schema_name='public', name='Public Tenant')
    domain_model = apps.get_model('tenants', 'Domain')
    domain_model.objects.create(domain=settings.DOMAIN, tenant=public_tenant, is_primary=True)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[
                    django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains',
                                             to='tenants.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(insert_public_tenant_and_domain),
    ]
